version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- cmd: dotnet restore src/Vlingo.Actors.sln
build:
  project: src/Vlingo.Actors.sln
  verbosity: minimal
  publish_nuget: true
test_script:
- cmd: dotnet test src/Vlingo.Actors.Tests
deploy:
- provider: NuGet
  api_key:
    secure: JBU8e40Z9+hXRUCgvpBdzYYVHhCnLwmlcw5SF020x+QXDgGfziLIpeHC9S3dTJGk
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master